apiVersion: v1
kind: PersistentVolume
metadata:
  name: logger-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/marmite"